### PR TITLE
CI: Move deployment to argocd 

### PR DESCRIPTION
**Pull request by BulatSaif**
Issue: https://github.com/paritytech/devops/issues/2977

## changes
`helm deploy` command was replaced by `argocd set/sync` command

helm values are [here](https://gitlab.parity-mgmt.parity.io/infrastructure/cloud-infra/-/merge_requests/3019)

### CODE REVIEW

**Review by alvicsam — APPROVED** [review]

**Comment by jsdw** [comment]
Does this change anything that we should be aware of when we come to trying to deploy telemetry, or is it just an underlying tweak to make life easier for you guys? :)

**Comment by BulatSaif** [comment]
> Does this change anything that we should be aware of when we come to trying to deploy telemetry, or is it just an underlying tweak to make life easier for you guys? :)

No, this will not affect the deployment in any way unless you have direct access to Kubernetes and use it to deploy manually. In this case, you would need to request access to ArgoCD. Gitlab-ci will work as usual.

**Comment by jsdw** [comment]
Brill, thank you!

In that case, I'm happy with this if you guys are!

**Review by jsdw — APPROVED** [review]

**Comment by ArshamTeymouri** [comment]
> Does this change anything that we should be aware of when we come to trying to deploy telemetry, or is it just an underlying tweak to make life easier for you guys? :)

The flow will be a bit different after merging this PR. Previously it was possible to deploy any arbitrary docker tags in prod or stg but now the flow has changes a bit and a new MR should be created in our [cloud-infra repo](https://gitlab.parity-mgmt.parity.io/infrastructure/cloud-infra) instead to change the docker tag.

The repo resides in our private gitlab instance so vpn has to be connected to access the web console. Additionally, you may need a new account created there to be able to login.
cc @jsdw @BulatSaif

**Pull request merged**
