### PR TITLE
Add turing-node icon

### PR DESCRIPTION
**Pull request by JNhua**

### CODE REVIEW

**Comment by JNhua** [comment]
[clabot:check]

**Comment by maciejhirsz** [comment]
Thanks for the PR! The icon looks cropped to me, is this how it's supposed to look?



I'm also afraid this will be hardly visible on non-retina screens.

**Comment by JNhua** [comment]
Thanks for your reminding. I have updated the "svg" in the latest "[commit](https://github.com/paritytech/substrate-telemetry/pull/159/commits/3bcddf0b3f01682247012808f498c9272de4a5b2)".

**Comment by maciejhirsz** [comment]
This is now deployed.

**Pull request merged**
