### PR TITLE
Update Darwinia Network Icons

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Darwinia is our mainnet like Polkadot.
Crab is our testnet like Kusama.

**Thank you!！**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
[clabot:check]

**Comment by AurevoirXavier** [comment]
[clabot:check]

**Comment by maciejhirsz** [comment]
@AurevoirXavier I can deploy this, but to make it work there needs to be a difference between node names for your mainnet and testnet.

The icons are for a node client, _not the chain_ they are on, and are matched to the string name of the node. All the nodes on the `Crab` network are `darwinia-network-darwinia`, stalled chains I can see used `darwinia-node`, those are the strings the icons are attached to.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier I can deploy this, but to make it work there needs to be a difference between node names for your mainnet and testnet.
> 
> The icons are for a node client, _not the chain_ they are on, and are matched to the string name of the node. All the nodes on the `Crab` network are `darwinia-network-darwinia`, stalled chains I can see used `darwinia-node`, those are the strings the icons should be attached to.

Thank you. I'll update the `impl_name`.

**Comment by maciejhirsz** [comment]
@AurevoirXavier cool, ping me back here to let me know what node names you settle on.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier cool, ping me back here to let me know what node names you settle on.

`Crab` and `Darwinia`. :)

**Comment by AurevoirXavier** [comment]
@maciejhirsz Are these changes online?

**Comment by maciejhirsz** [comment]
@AurevoirXavier last I checked the nodes still had old names. I'll check on a local build how it looks and push it out tomorrow morning :)

**Comment by maciejhirsz** [comment]
@AurevoirXavier it's now on live

**Pull request merged**
