### PR TITLE
WIP :: Docker images, terraform and dynamic connection

### PR DESCRIPTION
**Pull request by woss**
Changes are:

* no more monorepo since frontend is the only js app
* terraform digital ocean with docker, correct firewall settings , exposing for now only 3 ports
* full docker image builds (yeah docker pull already works)
* docker-compose dev and prod
* connection URL input field for quick and easy connection

### CODE REVIEW

**Comment by woss** [comment]
hi there, any update on this PR?

**Comment by maciejhirsz** [comment]
Hey @woss!

So I've been thinking about what to do with this PR for a while, I don't want to straight out reject it because you've obviously put quite some effort it, but I'm afraid in it's current form it's too big and touches too many things.

My general thoughts are:
+ Docker: I'm not sure our CLA permits having 3rd party maintainers listed in source files, but after some initial consultations I've had it appears the answer is "no". I'm not against having Dockerfile in the repo, but I think if you want to maintain the images (and take credit), then it should be elsewhere. If you want to make a separate repo for that, I'm happy to link to it (and/or images) in the README.
+ Combining the `common` package with `frontend`: great, no issues here.
+ Input for connection endpoint: undoubtedly useful, especially since it's something I hack around in dev, though I think it should be a build option, so I can disable it on the official telemetry.polkadot.io.
+ Formatting changes on top of moving things around in folders is making things a lot harder to review. In general, I believe it's best to stick to whatever formatting a project is using. It's one thing to fix indentation in places where it's inconsistent, and another to change all strings from single to double quotes. I don't have strong feelings about what style we should be using, but I'd prefer to avoid merging PRs that apply automatic formatting across the whole project, and I'd prefer to avoid situations where contributors with different reformatting across the board :P.

So, couple of ideas how to move this forward:
1. If you can revert the formatting that would be an improvement, though I can imagine that's not particularly easy or doable given the scope of the changes, so if that's a pain I'd prefer if you open a new PR which formats the current `master` to the same style you have in this PR, and then once that is merged rebase this PR so we have clearer history of actual changes.
2. Separate Docker from FE changes to separate PR, so we can at least discuss further how to approach that topic.

Sorry for the wall of text, hope I'm not being unreasonable.

**Comment by woss** [comment]
Hi, 
thanks for the reply. 
> Docker: I'm not sure our CLA permits having 3rd party maintainers listed in source files

**Comment by woss** [comment]
Hi, 
thanks for the reply. 

> Docker: I'm not sure our CLA permits having 3rd party maintainers listed in source files ...

I needed to test it out, and easiest was to add my own images. If you don't want to maintain this, no prob, i'll change the PR and exclude the Dockerfile and maintain the images myself. If you want to maintain them feel free, i don't care is my name mentioned or not.

> Input for connection endpoint: ...

I agree, maybe adding the `telemetry.polkadot.io` as a default?

> Formatting changes on top of moving things around...

If you can provide the `.prettierrc` or other formating rules i don't mind fixing this, but without it it's really hard to know exactly which set of rules you used since you never added them into the project. they are probably defaults for your editor.

**Comment by woss** [comment]
also you can reach out to me on your channels on riot. @woss

**Comment by chevdor** [comment]
Hi @woss. I pinged you on Riot. It think the content of this PR is awesome and I am glad @maciejhirsz pointed me to it because I was planning on doing something similar.
Let's have a chat to see how we can bring this PR forward. Maybe I can help.

**Comment by chevdor** [comment]
After reviewing this PR, I can't say enough that I like much of the content @woss !
This is huge however and a mix of many topics which is likely the reason why this PR was not merged yet.

It contains also scripts that "cannot work" such as the one pushing docker images to `woss/whatever...`. I have no doubt it work for @woss but it won't for the others.

My proposal would be (and I am happy if I can help) to create smaller PRs and remove the content from this one. At the end, we can see what is left :)

I think we could split:
- Docker work frontend
- Docker work backend
- URL config component
- Terraform work

**Pull request closed without merging**
